# Generated by Django 3.2.7 on 2021-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='client',
            field=models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('TELEGRAM', 'Telegram Bot'), ('WEB', 'Website'), ('ADMIN', 'Admin'), ('NA', 'Not Available')], default='NA', max_length=16),
        ),
    ]
