# Generated by Django 3.2.19 on 2023-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ttl',
            field=models.PositiveIntegerField(default=12, help_text='Time to live (Applies to non-permanent High Risk reports only)', verbose_name='TTL (hours)'),
        ),
    ]
