# Generated by Django 3.2.20 on 2023-10-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('static_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowYourRightsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('chapters', wagtail.fields.StreamField([('chapter', wagtail.blocks.StructBlock([('chapter_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(required=False)), ('sections', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']))]))]))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
