# Generated by Django 3.2.20 on 2023-10-06 18:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('static_page', '0002_knowyourrightspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPracticesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titles', wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('title_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('story_text', wagtail.blocks.TextBlock(required=False)), ('expert_analysis', wagtail.blocks.StreamBlock([('expert_analysis', wagtail.blocks.StructBlock([('expert_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('analysis', wagtail.blocks.RichTextBlock())]))]))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='chapters',
            field=wagtail.fields.StreamField([('chapter', wagtail.blocks.StructBlock([('chapter_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(required=False)), ('sections', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock())]))]))]))], use_json_field=True),
        ),
    ]
