# Generated by Django 3.2.20 on 2023-10-19 15:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0003_auto_20231006_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourrightspage',
            name='faqs',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
