# Generated by Django 3.2.20 on 2023-10-20 15:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('static_page', '0004_knowyourrightspage_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('questions', wagtail.fields.StreamField([('question', wagtail.blocks.StructBlock([('question', wagtail.blocks.TextBlock()), ('answer', wagtail.blocks.TextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock())], icon='help'))], use_json_field=True)),
            ],
            options={
                'verbose_name': 'User Guide',
                'verbose_name_plural': 'User Guides',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='knowyourrightspage',
            name='faqs',
        ),
        migrations.AddField(
            model_name='knowyourrightspage',
            name='faq_topics',
            field=wagtail.fields.StreamField([('topic', wagtail.blocks.StructBlock([('topic_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('issues', wagtail.blocks.StreamBlock([('issue', wagtail.blocks.StructBlock([('issue_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock(required=False)), ('faqs', wagtail.blocks.StreamBlock([('faq', wagtail.blocks.StructBlock([('faq_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock(required=False)), ('faq_text', wagtail.blocks.RichTextBlock())]))]))]))]))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='FaqPage',
        ),
    ]
