# Generated by Django 3.2.20 on 2023-10-26 15:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0005_auto_20231020_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpracticespage',
            name='titles',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('title_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('story_text', wagtail.blocks.RichTextBlock(required=False)), ('expert_analysis', wagtail.blocks.StreamBlock([('expert_analysis', wagtail.blocks.StructBlock([('expert_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('analysis', wagtail.blocks.RichTextBlock())]))]))]))], use_json_field=True),
        ),
    ]
