# Generated by Django 3.2.21 on 2023-10-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0006_alter_bestpracticespage_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourrightspage',
            name='faq_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourrightspage',
            name='faq_title',
            field=models.CharField(default='FAQ', max_length=250),
        ),
    ]
