# Generated by Django 3.2.21 on 2023-11-13 19:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0007_auto_20231030_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='chapters',
            field=wagtail.fields.StreamField([('chapter', wagtail.blocks.StructBlock([('chapter_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('sections', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock())]))]))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='faq_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='faq_topics',
            field=wagtail.fields.StreamField([('topic', wagtail.blocks.StructBlock([('topic_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('issues', wagtail.blocks.StreamBlock([('issue', wagtail.blocks.StructBlock([('issue_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faqs', wagtail.blocks.StreamBlock([('faq', wagtail.blocks.StructBlock([('faq_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faq_text', wagtail.blocks.RichTextBlock())]))]))]))]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
