# Generated by Django 3.2.22 on 2023-11-14 15:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0008_auto_20231113_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='chapters',
            field=wagtail.fields.StreamField([('chapter', wagtail.blocks.StructBlock([('chapter_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('sections', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock())], label_format='{title}'))]))], label_format='{title}'))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='faq_topics',
            field=wagtail.fields.StreamField([('topic', wagtail.blocks.StructBlock([('topic_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('issues', wagtail.blocks.StreamBlock([('issue', wagtail.blocks.StructBlock([('issue_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faqs', wagtail.blocks.StreamBlock([('faq', wagtail.blocks.StructBlock([('faq_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faq_text', wagtail.blocks.RichTextBlock())], label_format='{title}'))]))], label_format='{title}'))]))], label_format='{title}'))], blank=True, null=True, use_json_field=True),
        ),
    ]
