# Generated by Django 3.2.23 on 2023-12-05 19:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0009_auto_20231114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpracticespage',
            name='titles',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('title_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('story_text', wagtail.blocks.RichTextBlock(required=False)), ('expert_analysis', wagtail.blocks.StreamBlock([('expert_analysis', wagtail.blocks.StructBlock([('expert_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('analysis', wagtail.blocks.RichTextBlock())], label_format='{title}'))]))], label_format='{title}'))], use_json_field=True),
        ),
    ]
