# Generated by Django 3.2.23 on 2024-01-08 14:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0010_alter_bestpracticespage_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='faq_topics',
            field=wagtail.fields.StreamField([('topic', wagtail.blocks.StructBlock([('topic_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('issues', wagtail.blocks.StreamBlock([('issue', wagtail.blocks.StructBlock([('issue_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faqs', wagtail.blocks.StreamBlock([('faq', wagtail.blocks.StructBlock([('faq_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('faq_text', wagtail.blocks.RichTextBlock())], label_format='{title}'))]))], label_format='{title}'))]))], label_format='{title}'))], blank=True, null=True, use_json_field=True),
        ),
    ]
