# Generated by Django 3.2.23 on 2024-01-12 13:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_page', '0011_alter_knowyourrightspage_faq_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourrightspage',
            name='chapters',
            field=wagtail.fields.StreamField([('chapter', wagtail.blocks.StructBlock([('chapter_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('sections', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('section_id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('section_text', wagtail.blocks.RichTextBlock())], label_format='{title}'))], required=False))], label_format='{title}'))], use_json_field=True),
        ),
    ]
